### ISSUE TITLE
Node sync stuck

### ISSUE THREAD

**Issue by Baal19** [sx-network/validator#1]
hello, my SX node is stuck at block 11145199 .
The logs just print these messages over and over
```
Dec 24 00:47:21 sx main[7523]: 2022-12-24T00:47:21.324Z [DEBUG] polygon.server.sync-peer-client: received status from non-connected peer, ignore: id=16Uiu2HAmAYbpcB42mAbMtQJKjeXYWqHqvS8tSm485KMDjazHQWdE
Dec 24 00:47:21 sx main[7523]: 2022-12-24T00:47:21.328Z [DEBUG] polygon.server.sync-peer-client: received status from non-connected peer, ignore: id=16Uiu2HAm9HKUmFCACg5fnDQqfwcMUasV5yUsjFZSnHQiUEKC4Puf
Dec 24 00:47:21 sx main[7523]: 2022-12-24T00:47:21.328Z [DEBUG] polygon.server.sync-peer-client: received status from non-connected peer, ignore: id=16Uiu2HAm3NrpXurPhm5ZwWzA9prhYzqbV46YUyzX3iRnXgxgyYuG
Dec 24 00:47:21 sx main[7523]: 2022-12-24T00:47:21.329Z [DEBUG] polygon.server.sync-peer-client: received status from non-connected peer, ignore: id=16Uiu2HAm4BmetKSxGE7fdMEbnE9xaqCj4ScHwMEmNLCv8tmTuN6G
Dec 24 00:47:21 sx main[7523]: 2022-12-24T00:47:21.330Z [DEBUG] polygon.server.sync-peer-client: received status from non-connected peer, ignore: id=16Uiu2HAmT85ndMyP39VKkg5NMeoowv82twrBtpT1kRg3dhhTLTUF
Dec 24 00:47:21 sx main[7523]: 2022-12-24T00:47:21.330Z [DEBUG] polygon.server.sync-peer-client: received status from non-connected peer, ignore: id=16Uiu2HAmBcy36UHLxtoUUvexkUqBxHuvLfZX7VYg7ykZoSz3yqYH
Dec 24 00:47:21 sx main[7523]: 2022-12-24T00:47:21.500Z [DEBUG] polygon.server.sync-peer-client: received status from non-connected peer, ignore: id=16Uiu2HAmSYcSPH2ecd9cUUXPdyCUQDEzjJX1kts7NdeLaFpNsfrU
```
Thanks!

**Comment by dankostiuk** [comment]
Hey @Baal19 , 

Please pull the latest on `master`, we've added a fork at block 11145200 to the [genesis.json](https://github.com/sx-network/validator/blob/master/genesis.json) for our upcoming SX Merge which includes an initial step towards decentralizing the reporting of market outcomes.

Once you've checked out the latest, please run `update_validator.sh`:

```
git pull && chmod +x update_validator.sh && ./update_validator.sh "$(curl http://checkip.amazonaws.com)"
```

**Comment by Baal19** [comment]
Thanks for your answer. I was running already the update code, but I tried again just to be sure.
After the update the same error happens but at block 10504700 (I did a resync from scratch). For reference, I am running a node for RPC purposes only, not a validator node.

**Comment by dankostiuk** [comment]
Thanks for bringing this to our attention @Baal19 , could you try one last thing and add the `bootnode_only_sync: true` property to your config.yml (and rsync from scratch)?  See https://github.com/sx-network/validator#running-your-node-in-safety-mode for more details how to do this.

We suspect your node might be trying to sync with some peers that have invalid data as a result of the fork so setting this flag restricts your node to only sync from our bootnode validators.

Let me know if that resolves your issue.. we appreciate your patience 🙂

**Comment by Baal19** [comment]
Hello again @dankostiuk , unfortunately I am again stuck at block 11145199. Please let me know if you need any additional information.
All the config.yml settings (except for the RPC port, and bootnode_only_sync: true as suggested ) are the default ones from the installation script.

**Comment by 0xChupaCabra** [comment]
I am experiencing the same problem

**Comment by dankostiuk** [comment]
Hello @Baal19 and @stepollo2 ,

Could you please provide the details of the environment and instance you are running on and share your terminal output when running the command below:

```
git pull && chmod +x update_validator.sh && ./update_validator.sh "$(curl http://checkip.amazonaws.com)"
```

I suspect there may be an issue in the step that builds the binary, especially if either of you are running on a non-AWS environment. I tried myself on a fresh t2.small ec2 instance and was able to sync beyond the block you are stuck at. 

Thanks!

**Comment by Baal19** [comment]
```
git pull && chmod +x update_validator.sh && ./update_validator.sh "$(curl http://checkip.amazonaws.com)"
Already up to date.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     36      0 --:--:-- --:--:-- --:--:--    36
[Unit]
Description=SX Node Service
After=network.target
[Service]
Type=simple
Restart=always
RestartSec=1
User=baal
LimitNOFILE=100000
WorkingDirectory=/home/baal/validator/sx-node
ExecStart=/home/baal/validator/sx-node/main server --config config.yml
[Install]
WantedBy=multi-user.target
chain_config: /home/baal/validator/sx-node/genesis.json
data_dir: /home/baal/validator/sx-node/data
block_gas_target: 0x3938700
grpc_addr: 0.0.0.0:10000
jsonrpc_addr: 0.0.0.0:10002
network:
  libp2p_addr: 0.0.0.0:10001
  nat_addr: 86.99.247.194
seal: true
tx_pool:
  price_limit: 1000000000
log_level: DEBUG
gasprice_block_utilization_threshold: 0.95
data_feed:
  verify_outcome_api_url: https://outcome-reporter.sx.technology/api/outcome
Updating sx-node service...
Already up to date.
go build -o polygon-edge -ldflags="\
        -X 'github.com/0xPolygon/polygon-edge/versioning.Version=v0.6.0' \
        -X 'github.com/0xPolygon/polygon-edge/versioning.Commit=b774553efdf401c854f3ccbf8a9e87e3de29dad7'\
        -X 'github.com/0xPolygon/polygon-edge/versioning.Branch=develop'\
        -X 'github.com/0xPolygon/polygon-edge/versioning.BuildTime=Mon Jan 16 10:20:03 AM UTC 2023'" \
main.go
Service successfully updated! Press any key to continue...
```
My node is running in a Ubuntu 22.04 LTS (GNU/Linux 5.15.0-56-generic x86_64) Virtual Machine inside a dedicated server @dankostiuk

**Comment by 0xbobdylan** [comment]
Hello @dankostiuk I have the same problem, node is stuck at block 11145199. Here's my config, I have the latest version:

```
chain_config: ./genesis.json
secrets_config: ""
data_dir: "sx_data"
block_gas_target: 0x3938700
grpc_addr: 0.0.0.0:10000
jsonrpc_addr: 0.0.0.0:10002
network:
  libp2p_addr: 0.0.0.0:10001
  nat_addr: 127.0.0.1
  bootnode_only_sync: true
seal: true
tx_pool:
  price_limit: 1000000000
log_level: INFO
gasprice_block_utilization_threshold: 0.95
data_feed:
  verify_outcome_api_url: https://outcome-reporter.sx.technology/api/outcome
```

I'm getting the following errors: 

`[WARN]  polygon.syncer: failed to complete bulk sync with peer, try to next one: peer ID=error 16Uiu2HAm4cGCPV28nqTYgyPinsWUZGsze1eYJezNRf5P1RjBBRXm="unable to verify block, failed to verify the header: proposer seal by non-validator"`

**Comment by 0xChupaCabra** [comment]
i tried to build manually the sx binaries and sync is stuck at the same block. it would be nice to have a solution

**Comment by ghost** [comment]
Hello, my SX node is stuck at block 11145199 .

**Comment by dankostiuk** [comment]
> ```
> git pull && chmod +x update_validator.sh && ./update_validator.sh "$(curl http://checkip.amazonaws.com)"
> Already up to date.
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    14  100    14    0     0     36      0 --:--:-- --:--:-- --:--:--    36
> [Unit]
> Description=SX Node Service
> After=network.target
> [Service]
> Type=simple
> Restart=always
> RestartSec=1
> User=baal
> LimitNOFILE=100000
> WorkingDirectory=/home/baal/validator/sx-node
> ExecStart=/home/baal/validator/sx-node/main server --config config.yml
> [Install]
> WantedBy=multi-user.target
> chain_config: /home/baal/validator/sx-node/genesis.json
> data_dir: /home/baal/validator/sx-node/data
> block_gas_target: 0x3938700
> grpc_addr: 0.0.0.0:10000
> jsonrpc_addr: 0.0.0.0:10002
> network:
>   libp2p_addr: 0.0.0.0:10001
>   nat_addr: 86.99.247.194
> seal: true
> tx_pool:
>   price_limit: 1000000000
> log_level: DEBUG
> gasprice_block_utilization_threshold: 0.95
> data_feed:
>   verify_outcome_api_url: https://outcome-reporter.sx.technology/api/outcome
> Updating sx-node service...
> Already up to date.
> go build -o polygon-edge -ldflags="\
>         -X 'github.com/0xPolygon/polygon-edge/versioning.Version=v0.6.0' \
>         -X 'github.com/0xPolygon/polygon-edge/versioning.Commit=b774553efdf401c854f3ccbf8a9e87e3de29dad7'\
>         -X 'github.com/0xPolygon/polygon-edge/versioning.Branch=develop'\
>         -X 'github.com/0xPolygon/polygon-edge/versioning.BuildTime=Mon Jan 16 10:20:03 AM UTC 2023'" \
> main.go
> Service successfully updated! Press any key to continue...
> ```
> 
> My node is running in a Ubuntu 22.04 LTS (GNU/Linux 5.15.0-56-generic x86_64) Virtual Machine inside a dedicated server @dankostiuk

Hi @Baal19 ,

I noticed here that you are running off the latest `develop` branch on sx-node - please make sure to check out `main` as that is what we are running on SX Network Mainnet.

The initial command you ran when calling init_validator should have specified to use the branch `main` as mentioned in our docs:
```
git clone https://github.com/sx-network/validator.git && cd validator && chmod +x init_validator.sh && ./init_validator.sh "$(curl http://checkip.amazonaws.com)" main
```

The init_validator.sh is not intended to be run directly and since https://github.com/sx-network/sx-node previously had `develop` as the default branch, my guess is that you are running the latest `develop` which is incompatible with our chain once our node has synced up to 11145199.

Please try one last time ensuring your sx-node directory has `main` checked out and let me know the results.

Thanks!

**Comment by 0xChupaCabra** [comment]
i was able to pass the fork block using main branch, thanks for the help @dankostiuk

**Comment by Baal19** [comment]
Hello, i resolved too.

**Comment by dankostiuk** [comment]
Happy to hear it's all sorted out now @stepollo2, @Baal19 - will close this issue ✅
